services:
  mongo:
    image: mongo:8.0.4
    profiles: [db]
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes: 
      - moreflix:/data/db
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    profiles: [db]
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
  moreflix:
    image: tarof429/moreflix:${MOREFLIX_VERSION}
    profiles: [app]
    ports:
      - 5000:5000
    environment:
      MONGODB_USER: ${MONGO_ROOT_USERNAME}
      MONGODB_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGODB_SERVER: ${MONGODB_SERVER}
      MONGODB_PORT: ${MONGODB_PORT}
    depends_on:
      - mongo
volumes:
  moreflix:
